# Generated by Django 5.1 on 2024-12-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("aadhar_no", models.CharField(max_length=12, unique=True)),
                ("aadhar_card", models.FileField(upload_to="aadhar_cards/")),
                ("aadhar_verified", models.BooleanField(default=False)),
                ("highest_education", models.CharField(max_length=100)),
                ("university_name", models.CharField(max_length=255)),
                ("institute_name", models.CharField(max_length=255)),
                ("pass_out_date", models.DateField()),
                ("roll_number", models.CharField(max_length=50, unique=True)),
                (
                    "cgpa_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("education_doc", models.FileField(upload_to="education_docs/")),
                (
                    "gate_registration_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "gate_test_paper",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("gate_exam_date", models.DateField(blank=True, null=True)),
                (
                    "gate_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("gate_air_rank", models.IntegerField(blank=True, null=True)),
                (
                    "gate_scorecard",
                    models.FileField(
                        blank=True, null=True, upload_to="gate_scorecards/"
                    ),
                ),
            ],
        ),
    ]
