# Generated by Django 5.1.3 on 2024-12-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="xMarksheet_verified",
            field=models.BooleanField(default=False),
        ),
    ]
