# Generated by Django 5.1 on 2024-12-12 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_userdetails_xmarksheet_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdetails",
            old_name="aadhar_card",
            new_name="aadhar",
        ),
        migrations.RenameField(
            model_name="userdetails",
            old_name="phone",
            new_name="mobile_number",
        ),
        migrations.RenameField(
            model_name="userdetails",
            old_name="education_doc",
            new_name="xMarksheet",
        ),
    ]
